print("################\n")
print("##teste##\n")
print(" *")
print(" * *")
print(" * *")
print(" * *")
print("*** ***")
print(" * *")
print(" * *")
print(" *****\n")
##################
print("    ## original ##\n")
print("          *")
print("         * *")
print("        *   *")
print("       *     *")
print("      ***   ***")
print("        *   *")
print("        *   *")
print("        *****\n")
###################
print("## com menos 'print()' ##\n")
print("          *\n         * *\n        *   *\n       *     *\n      ***   ***\n        *   *\n        *   *\n        *****\n")
###################
print("     ## maior ##\n")
print("          *\n         * *\n        *   *\n       *     *\n      *       *\n     *         *\n    *           *\n   *             *\n  *               *\n ******       ******\n      *       *\n      *       *\n      *       *\n      *       *\n      *       *\n      *********\n")
print("##flecha duplicada##")
print("          *           "*2)
print("         * *          "*2)
print("        *   *         "*2)
print("       *     *        "*2)
print("      *       *       "*2)
print("     *         *      "*2)
print("    *           *     "*2)
print("   *             *    "*2)
print("  *               *   "*2)
print(" *                 *  "*2)
print("******         ****** "*2)
print("     *         *      "*2)
print("     *         *      "*2)
print("     *         *      "*2)
print("     *         *      "*2)
print("     ***********      "*2)